-- Etiquetas reutilizables para tareas
-- Ejecuta este SQL en el SQL Editor de Supabase (Dashboard → SQL → New query)

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null default '#feef4c',
  user_id uuid references auth.users (id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now()
);

create unique index if not exists tags_user_name_idx
  on public.tags (user_id, lower(name));

alter table public.tasks
  add column if not exists tag_id bigint references public.tags (id) on delete set null;

alter table public.tags enable row level security;

drop policy if exists "Users can select own tags" on public.tags;
drop policy if exists "Users can insert own tags" on public.tags;
drop policy if exists "Users can update own tags" on public.tags;
drop policy if exists "Users can delete own tags" on public.tags;

create policy "Users can select own tags"
  on public.tags for select
  using (auth.uid() = user_id);

create policy "Users can insert own tags"
  on public.tags for insert
  with check (auth.uid() = user_id);

create policy "Users can update own tags"
  on public.tags for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own tags"
  on public.tags for delete
  using (auth.uid() = user_id);
