-- Perfiles y contactos (para conectar usuarios por correo y luego compartir tareas)
-- Ejecuta este SQL en Supabase → SQL Editor → Run

-- 1) Perfiles públicos mínimos (uno por usuario autenticado)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx
  on public.profiles (lower(email));

-- 2) Contactos (relación: yo → contacto)
-- FK a profiles para poder hacer join desde el cliente (Supabase/PostgREST)
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  contact_user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint contacts_not_self check (user_id <> contact_user_id),
  constraint contacts_unique_pair unique (user_id, contact_user_id)
);

-- 3) Crear perfil automáticamente al registrarse
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(
      nullif(trim(new.raw_user_meta_data->>'display_name'), ''),
      nullif(trim(new.raw_user_meta_data->>'alias'), ''),
      split_part(new.email, '@', 1)
    )
  )
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 4) Rellenar perfiles de usuarios que ya existen
insert into public.profiles (id, email, display_name)
select
  u.id,
  u.email,
  coalesce(
    nullif(trim(u.raw_user_meta_data->>'display_name'), ''),
    nullif(trim(u.raw_user_meta_data->>'alias'), ''),
    split_part(u.email, '@', 1)
  )
from auth.users u
on conflict (id) do update
  set email = excluded.email,
      updated_at = now();

-- 5) Asegurar mi perfil (útil al abrir la app)
create or replace function public.ensure_my_profile()
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  u auth.users%rowtype;
  p public.profiles%rowtype;
begin
  if me is null then
    raise exception 'No autenticado';
  end if;

  select * into u from auth.users where id = me;

  insert into public.profiles (id, email, display_name)
  values (
    u.id,
    u.email,
    coalesce(
      nullif(trim(u.raw_user_meta_data->>'display_name'), ''),
      nullif(trim(u.raw_user_meta_data->>'alias'), ''),
      split_part(u.email, '@', 1)
    )
  )
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now()
  returning * into p;

  return p;
end;
$$;

-- 6) Conectar contacto por correo (solo si el correo existe)
create or replace function public.add_contact_by_email(contact_email text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  target public.profiles%rowtype;
  normalized text := lower(trim(contact_email));
begin
  if me is null then
    return json_build_object('ok', false, 'error', 'not_authenticated');
  end if;

  if normalized is null or normalized = '' or position('@' in normalized) = 0 then
    return json_build_object('ok', false, 'error', 'invalid_email');
  end if;

  -- Asegurar que yo tengo perfil
  perform public.ensure_my_profile();

  select * into target
  from public.profiles
  where lower(email) = normalized
  limit 1;

  if not found then
    return json_build_object('ok', false, 'error', 'not_found');
  end if;

  if target.id = me then
    return json_build_object('ok', false, 'error', 'self');
  end if;

  insert into public.contacts (user_id, contact_user_id)
  values (me, target.id)
  on conflict (user_id, contact_user_id) do nothing;

  return json_build_object(
    'ok', true,
    'contact', json_build_object(
      'id', target.id,
      'email', target.email,
      'display_name', coalesce(nullif(trim(target.display_name), ''), split_part(target.email, '@', 1))
    )
  );
end;
$$;

grant execute on function public.ensure_my_profile() to authenticated;
grant execute on function public.add_contact_by_email(text) to authenticated;

-- 7) RLS
alter table public.profiles enable row level security;
alter table public.contacts enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can view contact profiles" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;

create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can view contact profiles"
  on public.profiles for select
  using (
    exists (
      select 1 from public.contacts c
      where c.user_id = auth.uid()
        and c.contact_user_id = profiles.id
    )
  );

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can select own contacts" on public.contacts;
drop policy if exists "Users can delete own contacts" on public.contacts;

create policy "Users can select own contacts"
  on public.contacts for select
  using (auth.uid() = user_id);

create policy "Users can delete own contacts"
  on public.contacts for delete
  using (auth.uid() = user_id);
