-- Compartir tareas con contactos
-- Ejecuta en Supabase → SQL Editor → Run

create table if not exists public.task_shares (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks (id) on delete cascade,
  shared_with uuid not null references public.profiles (id) on delete cascade,
  shared_by uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now(),
  constraint task_shares_unique unique (task_id, shared_with),
  constraint task_shares_not_self check (shared_with <> shared_by)
);

alter table public.task_shares enable row level security;

drop policy if exists "Users can select related task shares" on public.task_shares;
drop policy if exists "Users can insert own task shares" on public.task_shares;
drop policy if exists "Users can delete own task shares" on public.task_shares;

create policy "Users can select related task shares"
  on public.task_shares for select
  using (auth.uid() = shared_by or auth.uid() = shared_with);

create policy "Users can insert own task shares"
  on public.task_shares for insert
  with check (auth.uid() = shared_by);

create policy "Users can delete own task shares"
  on public.task_shares for delete
  using (auth.uid() = shared_by);

-- Trae tareas compartidas conmigo para una fecha (bypass seguro de RLS de tasks)
create or replace function public.get_shared_tasks_for_date(target_date text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  result json;
begin
  if me is null then
    return '[]'::json;
  end if;

  select coalesce(json_agg(row_to_json(t)), '[]'::json)
  into result
  from (
    select
      tasks.*,
      case
        when tags.id is null then null
        else json_build_object('id', tags.id, 'name', tags.name, 'color', tags.color)
      end as tags
    from public.tasks
    join public.task_shares s on s.task_id = tasks.id
    left join public.tags on tags.id = tasks.tag_id
    where s.shared_with = me
      and tasks.date = target_date
    order by tasks.order_index asc
  ) t;

  return result;
end;
$$;

grant execute on function public.get_shared_tasks_for_date(text) to authenticated;
