-- Checklist / lista de ítems por tarea
-- Ejecuta en Supabase → SQL Editor → Run

create table if not exists public.task_checklist_items (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks (id) on delete cascade,
  title text not null,
  is_completed boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists task_checklist_items_task_id_idx
  on public.task_checklist_items (task_id);

alter table public.task_checklist_items enable row level security;

drop policy if exists "Authenticated can select checklist items" on public.task_checklist_items;
drop policy if exists "Authenticated can insert checklist items" on public.task_checklist_items;
drop policy if exists "Authenticated can update checklist items" on public.task_checklist_items;
drop policy if exists "Authenticated can delete checklist items" on public.task_checklist_items;

create policy "Authenticated can select checklist items"
  on public.task_checklist_items for select
  to authenticated
  using (true);

create policy "Authenticated can insert checklist items"
  on public.task_checklist_items for insert
  to authenticated
  with check (true);

create policy "Authenticated can update checklist items"
  on public.task_checklist_items for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated can delete checklist items"
  on public.task_checklist_items for delete
  to authenticated
  using (true);
