-- Listas con nombre por tarea (varias listas por tarea)
-- Ejecuta en Supabase → SQL Editor → Run

create table if not exists public.task_lists (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists task_lists_task_id_idx
  on public.task_lists (task_id);

-- Ítems de cada lista
create table if not exists public.task_list_items (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.task_lists (id) on delete cascade,
  title text not null,
  is_completed boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists task_list_items_list_id_idx
  on public.task_list_items (list_id);

alter table public.task_lists enable row level security;
alter table public.task_list_items enable row level security;

drop policy if exists "Authenticated can select task lists" on public.task_lists;
drop policy if exists "Authenticated can insert task lists" on public.task_lists;
drop policy if exists "Authenticated can update task lists" on public.task_lists;
drop policy if exists "Authenticated can delete task lists" on public.task_lists;

create policy "Authenticated can select task lists"
  on public.task_lists for select to authenticated using (true);
create policy "Authenticated can insert task lists"
  on public.task_lists for insert to authenticated with check (true);
create policy "Authenticated can update task lists"
  on public.task_lists for update to authenticated using (true) with check (true);
create policy "Authenticated can delete task lists"
  on public.task_lists for delete to authenticated using (true);

drop policy if exists "Authenticated can select task list items" on public.task_list_items;
drop policy if exists "Authenticated can insert task list items" on public.task_list_items;
drop policy if exists "Authenticated can update task list items" on public.task_list_items;
drop policy if exists "Authenticated can delete task list items" on public.task_list_items;

create policy "Authenticated can select task list items"
  on public.task_list_items for select to authenticated using (true);
create policy "Authenticated can insert task list items"
  on public.task_list_items for insert to authenticated with check (true);
create policy "Authenticated can update task list items"
  on public.task_list_items for update to authenticated using (true) with check (true);
create policy "Authenticated can delete task list items"
  on public.task_list_items for delete to authenticated using (true);
