-- Hábitos: definición + registro diario de cumplimiento
-- Ejecuta en Supabase → SQL Editor → Run

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  name text not null,
  -- 0 = domingo … 6 = sábado (igual que Date.getDay() / JS)
  weekdays smallint[] not null default '{1,2,3,4,5}',
  created_at timestamptz not null default now(),
  constraint habits_name_not_empty check (char_length(trim(name)) > 0),
  constraint habits_weekdays_not_empty check (cardinality(weekdays) > 0)
);

create index if not exists habits_user_id_idx on public.habits (user_id);

create table if not exists public.habit_logs (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  date date not null,
  created_at timestamptz not null default now(),
  unique (habit_id, date)
);

create index if not exists habit_logs_user_date_idx
  on public.habit_logs (user_id, date);

create index if not exists habit_logs_habit_id_idx
  on public.habit_logs (habit_id);

alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;

drop policy if exists "Users can select own habits" on public.habits;
drop policy if exists "Users can insert own habits" on public.habits;
drop policy if exists "Users can update own habits" on public.habits;
drop policy if exists "Users can delete own habits" on public.habits;

create policy "Users can select own habits"
  on public.habits for select
  using (auth.uid() = user_id);

create policy "Users can insert own habits"
  on public.habits for insert
  with check (auth.uid() = user_id);

create policy "Users can update own habits"
  on public.habits for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own habits"
  on public.habits for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own habit logs" on public.habit_logs;
drop policy if exists "Users can insert own habit logs" on public.habit_logs;
drop policy if exists "Users can delete own habit logs" on public.habit_logs;

create policy "Users can select own habit logs"
  on public.habit_logs for select
  using (auth.uid() = user_id);

create policy "Users can insert own habit logs"
  on public.habit_logs for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.habits h
      where h.id = habit_id and h.user_id = auth.uid()
    )
  );

create policy "Users can delete own habit logs"
  on public.habit_logs for delete
  using (auth.uid() = user_id);
